export const temporaryData = {
  page: 1,
  totalPages: 20,
  totalBalance: 250,
  transactions: [
    {
      id: '00001',
      date: '1 apr 1960',
      owner: null,
      income: 'increase',
      category: '001',
      comment: 'yay, got money!',
      sum: 1000,
      balance: 1000,
    },
    {
      id: '00002',
      date: '1 apr 1961',
      owner: null,
      income: 'decrease',
      category: '002',
      comment: 'rent(',
      sum: 500,
      balance: 500,
    },
    {
      id: '00003',
      date: '1 apr 1962',
      owner: null,
      income: 'decrease',
      category: '003',
      comment: 'Yummy food so yummy mommy',
      sum: 310,
      balance: 190,
    },
    {
      id: '00004',
      date: '1 apr 1963',
      owner: null,
      income: 'increase',
      category: '001',
      comment: 'got a gift, super!',
      sum: 175,
      balance: 365,
    },
    {
      id: '00005',
      date: '1 apr 1964',
      owner: null,
      income: 'decrease',
      category: '003',
      comment: 'Two croissans and a coffee',
      sum: 115,
      balance: 250,
    },
    {
      id: '00006',
      date: '1 apr 1965',
      owner: null,
      income: 'increase',
      category: '001',
      comment: 'yay, got money!',
      sum: 1000,
      balance: 1000,
    },
    {
      id: '00007',
      date: '1 apr 1966',
      owner: null,
      income: 'decrease',
      category: '002',
      comment: 'rent(',
      sum: 500,
      balance: 500,
    },
    {
      id: '00008',
      date: '1 apr 1967',
      owner: null,
      income: 'decrease',
      category: '003',
      comment: 'Yummy food so yummy mommy',
      sum: 310,
      balance: 190,
    },
    {
      id: '00009',
      date: '1 apr 1968',
      owner: null,
      income: 'increase',
      category: '001',
      comment: 'got a gift, super!',
      sum: 175,
      balance: 365,
    },
    {
      id: '00010',
      date: '1 apr 1969',
      owner: null,
      income: 'decrease',
      category: '003',
      comment: 'Two croissans and a coffee',
      sum: 115,
      balance: 250,
    },
    {
      id: '00011',
      date: '1 apr 1970',
      owner: null,
      income: 'increase',
      category: '001',
      comment: 'yay, got money!',
      sum: 1000,
      balance: 1000,
    },
    {
      id: '00012',
      date: '1 apr 1971',
      owner: null,
      income: 'decrease',
      category: '002',
      comment: 'rent(',
      sum: 500,
      balance: 500,
    },
    {
      id: '00013',
      date: '1 apr 1972',
      owner: null,
      income: 'decrease',
      category: '003',
      comment: 'Yummy food so yummy mommy',
      sum: 310,
      balance: 190,
    },
    {
      id: '00014',
      date: '1 apr 1973',
      owner: null,
      income: 'increase',
      category: '001',
      comment: 'got a gift, super!',
      sum: 175,
      balance: 365,
    },
    {
      id: '00015',
      date: '1 apr 1974',
      owner: null,
      income: 'decrease',
      category: '003',
      comment: 'Two croissans and a coffee',
      sum: 115,
      balance: 250,
    },
    {
      id: '00016',
      date: '1 apr 1975',
      owner: null,
      income: 'increase',
      category: '001',
      comment: 'yay, got money!',
      sum: 1000,
      balance: 1000,
    },
    {
      id: '00017',
      date: '1 apr 1976',
      owner: null,
      income: 'decrease',
      category: '002',
      comment: 'rent(',
      sum: 500,
      balance: 500,
    },
    {
      id: '00018',
      date: '1 apr 1977',
      owner: null,
      income: 'decrease',
      category: '003',
      comment: 'Yummy food so yummy mommy',
      sum: 310,
      balance: 190,
    },
    {
      id: '00019',
      date: '1 apr 1978',
      owner: null,
      income: 'increase',
      category: '001',
      comment: 'got a gift, super!',
      sum: 175,
      balance: 365,
    },
    {
      id: '00020',
      date: '1 apr 1979',
      owner: null,
      income: 'decrease',
      category: '003',
      comment: 'Two croissans and a coffee',
      sum: 115,
      balance: 250,
    },
  ],
};
